#!/bin/bash

# Clean le projet
./cleanAll

# Récupération des dernières sources du projet
# echo "Récupération de la dernière version du projet"
# git pull --quiet

# Création de l'archive
echo "Creating archive..."
tar --no-xattrs --exclude='genDeliverable' --exclude='Deploiement' --exclude='Parametrage' --exclude='.git' --exclude='deliverables' -czf B2.BAUMARD.GUERRY.GUILLOU.MAQUENNE.PERE.logiciel.Etape6.tar.gz *
echo "Archive created with success!"
