#!/bin/bash

# Clean le projet
./cleanAll

# Récupération des dernières sources du projet
# echo "Récupération de la dernière version du projet"
# git pull --quiet

# Création de l'archive
echo "Creating archive..."
tar --no-xattrs --exclude='genDeliverable' --exclude='Deploiement' --exclude='Parametrage' --exclude='.git' --exclude='deliverables/' --exclude='libraries/' -czf BAUMARD.GUILLOU.MAQUENNE.SIT213.Etape2.tar.gz *
echo "Archive created with success!"